### ISSUE TITLE
Doesn't work with Ensemble GTF files?

### ISSUE THREAD

**Issue by JonN17** [broadinstitute/gtex-pipeline#26]
Program works fine with Gencode but not Ensemble?  How do I get it to work?

**Steps to reproduce**
- wget ftp://ftp.ensembl.org/pub/release-97/gtf/homo_sapiens/Homo_sapiens.GRCh38.97.gtf.gz
- mkdir BUG
- pigz -d Homo_sapiens.GRCh38.97.gtf.gz > BUG/Homo_sapiens.GRCh38.97.gtf
- python3 SOFTWARE/gtex-pipeline/gene_model/collapse_annotation.py BUG/Homo_sapiens.GRCh38.97.gtf BUG/Homo_sapiens.GRCh38.97_compressed.gtf

**Error**
```
Traceback (most recent call last):
  File "SOFTWARE/gtex-pipeline/gene_model/collapse_annotation.py", line 249, in <module>
    annotation = Annotation(args.transcript_gtf)
  File "SOFTWARE/gtex-pipeline/gene_model/collapse_annotation.py", line 68, in __init__
    g = Gene(gene_id, attributes['gene_name'], attributes['gene_type'], chrom, strand, start_pos, end_pos)
KeyError: 'gene_type'
```

**Comment by francois-a** [comment]
This script is designed to be compatible with the [GENCODE GTF format](https://www.gencodegenes.org/pages/data_format.html), and it looks like your file is missing the `gene_type` attribute.

**Comment by JonN17** [comment]
Ok so no Ensemble GTF files.  And yes it's missing the gene_type attribute which is mandatory according to your link.  Thank you!

**Comment by francois-a** [comment]
Please see the v9 branch for a fix: https://github.com/broadinstitute/gtex-pipeline/blob/v9/gene_model/collapse_annotation.py and let me know if there are still issues.

**Comment by francois-a** [comment]
Resolved at https://github.com/broadinstitute/rnaseqc/issues/31.

**Comment by adomingues** [comment]
@francois-a sadly I have to report that there are several ensembl GTFs for which the script is still now working. I tested several species and it work for:
-  human
-  mouse
- Caenorhabditis elegans (v99)
- Danio rerio  (v99)

However the following species generate errors:
- Drosophila melanogaster
- Saccharomyces cerevisiae
- Macaca mulatta

The error tends to be `KeyError: 'gene_name'` and as far I can tell from looking at some of the entries, is due to genes / entries with missing `gene_names`, for instance `grep "ENSMMUG00000064799" Macaca_mulatta.Mmul_10.99.gtf`.

I supposed a simple workaround would be to add the missing entry in the form `gene_name "";` and report the gene_ids troublesome genes to stderr or stdout. Just an idea. Btw, when I say missing gene_name, it could be any non-essential entry such as transcript_name.

Below the reproducible example and generated errors:

```bash
## Saccharomyces cerevisiae
wget ftp://ftp.ensembl.org/pub/release-99/gtf/saccharomyces_cerevisiae/Saccharomyces_cerevisiae.R64-1-1.99.gtf.gz
gunzip Saccharomyces_cerevisiae.R64-1-1.99.gtf.gz

./collapse_annotation.py Saccharomyces_cerevisiae.R64-1-1.99.gtf collapsed.gtf

Traceback (most recent call last):
  File "./collapse_annotation.py", line 266, in <module>
    annotation = Annotation(args.transcript_gtf)
  File "./collapse_annotation.py", line 73, in __init__
    g = Gene(gene_id, attributes['gene_name'], attributes['gene_type'], chrom, strand, start_pos, end_pos)
KeyError: 'gene_name'


## Drosophila melanogaster
wget ftp://ftp.ensembl.org/pub/release-99/gtf/drosophila_melanogaster/Drosophila_melanogaster.BDGP6.28.99.gtf.gz

gunzip Drosophila_melanogaster.BDGP6.28.99.gtf.gz

./collapse_annotation.py Drosophila_melanogaster.BDGP6.28.99.gtf collapsed.gtf

Traceback (most recent call last):
  File "./collapse_annotation.py", line 266, in <module>
    annotation = Annotation(args.transcript_gtf)
  File "./collapse_annotation.py", line 81, in __init__
    t = Transcript(attributes.pop('transcript_id'), attributes.pop('transcript_name'),
KeyError: 'transcript_name'


## Macaca mulatta
wget ftp://ftp.ensembl.org/pub/release-99/gtf/macaca_mulatta/Macaca_mulatta.Mmul_10.99.gtf.gz

gunzip Macaca_mulatta.Mmul_10.99.gtf.gz

./collapse_annotation.py Macaca_mulatta.Mmul_10.99.gtf collapsed.gtf

Traceback (most recent call last):
  File "./collapse_annotation.py", line 266, in <module>
    annotation = Annotation(args.transcript_gtf)
  File "./collapse_annotation.py", line 73, in __init__
    g = Gene(gene_id, attributes['gene_name'], attributes['gene_type'], chrom, strand, start_pos, end_pos)
KeyError: 'gene_name
```

Cheers.

**Comment by francois-a** [comment]
Hi,

Thanks for the reproducible examples. The latest commit, 81bf691f2ae63a12d3c4c3d2da3943111729301a, should fix this
