### ISSUE TITLE
RNA-seQC output empty

### ISSUE THREAD

**Issue by silvernano** [broadinstitute/gtex-pipeline#48]
Hi, 

I followed the TOPmed pipeline used STAR to get the bam file, picard to mark duplicate, then used RNA-seQC to generate gene tpm.  All steps ran without any error, however the gene_tpm.gct file only contain nan for tpm column, and exon_reads.gct and other files contain only 0 for last column, the first two columns (ID and name) looks fine. 
head gene_tpm.gct
![image](https://user-images.githubusercontent.com/43122383/92510876-6133fa80-f1c1-11ea-8671-c1a233e811c2.png)

head exon_reads.gct
![image](https://user-images.githubusercontent.com/43122383/92510917-6f821680-f1c1-11ea-9279-2b59198b7f7a.png)

Therefore I double checked my work, and noticed a warning from picard mark duplicate step, because the log is very long, I will only paste the head and tail here:

![picardLOG](https://user-images.githubusercontent.com/43122383/92510080-24b3cf00-f1c0-11ea-92b1-e8790b3c7c12.jpeg)

![image](https://user-images.githubusercontent.com/43122383/92510504-d05d1f00-f1c0-11ea-9168-8f52fe98b2f6.png)

Did this cause the empty output? I've been searching online for solution for several days and did not get any valid results. 

Thank you for your help!

**Comment by francois-a** [comment]
Hi,

It looks like there's a problem with the MarkDuplicates step (because the read IDs don't have the expected format), but as long as the output BAM has all the alignments, that shouldn't be an issue for RNA-SeQC. Have you tried running it on the STAR BAM directly?

If that doesn't work either, can you please post this issue in the [RNA-SeQC repo](https://github.com/getzlab/rnaseqc)?

**Comment by silvernano** [comment]
Yes, I did try to use STAR BAM directly, and the results are the same. I will post it again in the RNA-SeQC repo. Thanks.
